# Generated by Django 4.2 on 2023-05-04 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_webapp', '0002_productmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='productimg'),
        ),
    ]
