# Generated by Django 4.2 on 2023-05-05 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce_webapp', '0005_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('ORDERD', 'orderd'), ('SHIPPED', 'shipped'), ('ON THE WAY', 'on the way'), ('DELIVERD', 'deliverd'), ('CANCELLED', 'cancelled')], max_length=30)),
                ('transaction_id', models.CharField(max_length=100, null=True, unique=True)),
                ('totalprice', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('ORDERD', 'orderd'), ('SHIPPED', 'shipped'), ('ON THE WAY', 'on the way'), ('DELIVERD', 'deliverd'), ('CANCELLED', 'cancelled')], max_length=30)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_webapp.order')),
            ],
        ),
    ]
