# Generated by Django 4.2 on 2023-05-05 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_webapp', '0007_alter_order_status_alter_orderitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
    ]
