# Generated by Django 4.2 on 2023-05-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_webapp', '0009_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('ORDERED', 'ordered'), ('SHIPPED', 'shipped'), ('ON THE WAY', 'on the way'), ('DELIVERD', 'deliverd'), ('CANCELLED', 'cancelled')], max_length=30),
        ),
    ]
