# Generated by Django 4.2 on 2023-05-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_webapp', '0010_alter_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='userimg'),
        ),
    ]
